"""Weyl equidistribution and Sarkozy's theorem via polynomial recurrence.

Weyl (1916): for irrational alpha, the sequences (n * alpha mod 1) and
(n^2 * alpha mod 1) are equidistributed on the circle.  The quadratic case
is dynamically generated by the skew product

    T(x, y) = (x + alpha, y + 2x + alpha)

whose orbit of (0,0) has second coordinate n^2 * alpha.  Because this
system is (uniquely) ergodic, the orbit is dense; in particular n^2 * alpha
returns arbitrarily close to 0 -- *polynomial recurrence*.

Furstenberg and Sarkozy (independently, 1977/78) upgraded this to a
striking arithmetic statement:

    If S is a set of integers of positive upper density, then there exist
    two elements of S whose difference is a nonzero perfect square.

Dynamically: mu(A) > 0 implies mu(A \\cap T^{-n^2} A) > 0 for some n.
This module verifies both the equidistribution inputs (via Weyl sums) and
the combinatorial output (square differences in explicit sets).
"""

from __future__ import annotations

import math
from typing import Iterable

import numpy as np

__all__ = [
    "weyl_sum",
    "discrepancy_star",
    "square_difference",
    "square_return_profile",
]


def weyl_sum(alpha: float, N: int, degree: int = 1) -> complex:
    """Normalised exponential sum (1/N) * sum_{n<N} e(n^degree * alpha).

    Equidistribution of (n^degree * alpha) is equivalent (Weyl criterion)
    to these sums tending to 0 for every nonzero integer multiple of alpha.
    """
    n = np.arange(N, dtype=float)
    return complex(np.exp(2j * np.pi * (n**degree) * alpha).mean())


def discrepancy_star(points: Iterable[float], grid: int = 1000) -> float:
    """Crude star discrepancy of points in [0,1): max deviation of empirical
    CDF from the uniform CDF over a grid of test intervals [0, t)."""
    x = np.sort(np.asarray(list(points)) % 1.0)
    N = x.size
    t = np.linspace(0, 1, grid, endpoint=False)
    emp = np.searchsorted(x, t, side="right") / N
    return float(np.max(np.abs(emp - t)))


def square_difference(S: Iterable[int]) -> tuple[int, int, int] | None:
    """Find a, b in S with a - b = n^2 > 0.  Returns (a, b, n) or None.

    Sarkozy's theorem guarantees success whenever S has positive upper
    density and is 'long enough'; this routine lets you watch the theorem
    come true on concrete sets.
    """
    s_sorted = sorted(set(S))
    sset = set(s_sorted)
    if not s_sorted:
        return None
    span = s_sorted[-1] - s_sorted[0]
    max_n = math.isqrt(span) if span > 0 else 0
    for n in range(1, max_n + 1):
        sq = n * n
        for b in s_sorted:
            if b + sq in sset:
                return b + sq, b, n
    return None


def square_return_profile(word: Iterable[int], n_max: int) -> np.ndarray:
    """Empirical mu(A \\cap T^{-n^2} A) for n = 1..n_max, where A is the
    cylinder of a 0/1 word: the density of m with m and m + n^2 both in S."""
    w = np.asarray(list(word), dtype=np.int8)
    N = w.size
    out = np.zeros(n_max)
    for i, n in enumerate(range(1, n_max + 1)):
        g = n * n
        if g >= N:
            break
        out[i] = float((w[: N - g] & w[g:]).sum()) / N
    return out
